title: Common Lisp Cookbook
description: A collection of examples of using Common Lisp
baseurl: "/cl-cookbook"

# https://stackoverflow.com/questions/39057405/unable-to-build-a-jekyll-site-invalid-date
exclude: [vendor]

markdown: kramdown

# Disable the default syntax highlighter, to make place to
# HighlightLisp (in JS).
kramdown:
    syntax_highlighter_opts:
      disable: true

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: "chapter"
